from __future__ import annotations

from dataclasses import dataclass
from typing import Literal

from .audit import AuditLogger
from .config import PermissionMode
from .workspace import Workspace


SkillMode = Literal["sandbox", "full_control"]


@dataclass(frozen=True)
class SkillSpec:
    name: str
    mode: SkillMode
    description: str
    implemented: bool
    permission_notes: str
    input_contract: tuple[str, ...] = ()
    output_contract: tuple[str, ...] = ()
    fallback_behavior: str = "Return an auditable degraded result when the backend is unavailable."
    requires_confirmation: bool = False
    status: str = "implemented"


SKILLS: tuple[SkillSpec, ...] = (
    SkillSpec(
        name="meeting_capture",
        mode="sandbox",
        description="Transcribe meetings, separate speakers, summarize decisions, and extract action items.",
        implemented=True,
        permission_notes="Requires explicit meeting mode. Does not parse projected content by default.",
        input_contract=("meeting title", "participants", "active transcript or imported transcript file"),
        output_contract=("minutes markdown", "transcript export", "decisions", "action items"),
        fallback_behavior="Block transcript append until meeting mode is explicitly enabled.",
    ),
    SkillSpec(
        name="document_workspace",
        mode="sandbox",
        description="Import user-approved files, summarize text, compare documents, and create report outlines.",
        implemented=True,
        permission_notes="Only reads files copied into the workspace or explicitly allowed roots.",
        input_contract=("workspace filename", "user-approved source path under allowed roots"),
        output_contract=("analysis JSON", "summary markdown", "comparison JSON", "report outline"),
        fallback_behavior="Reject files outside workspace/allowed roots and write a blocked audit event.",
    ),
    SkillSpec(
        name="paper_scan",
        mode="sandbox",
        description="Capture paper documents, enhance images, run OCR, and extract tables or contract clauses.",
        implemented=True,
        permission_notes="Requires camera permission and explicit scan action.",
        input_contract=("workspace image filename", "document type", "OCR language"),
        output_contract=("scan metadata JSON", "OCR request JSON", "structured extraction placeholder"),
        fallback_behavior="Return backend_missing until PaddleOCR or a camera capture adapter is configured.",
        status="adapter_ready",
    ),
    SkillSpec(
        name="projection_assistant",
        mode="sandbox",
        description="Render meeting summaries and confirmations to the projector surface.",
        implemented=True,
        permission_notes="Projection content is generated by the agent, not passively parsed.",
        input_contract=("title", "markdown body or card fields", "projection mode"),
        output_contract=("projection markdown path", "card mode", "audit event"),
        fallback_behavior="Write markdown cards to projection_out even when physical projector hardware is absent.",
    ),
    SkillSpec(
        name="desktop_operator",
        mode="full_control",
        description="Operate the connected computer through approved workflows and GUI automation.",
        implemented=True,
        permission_notes="Requires OPENCLAW_PERMISSION_MODE=full_control and per-task confirmation.",
        input_contract=("task description", "approved workflow steps", "explicit user confirmation"),
        output_contract=("workflow plan", "permission decision", "audit event"),
        fallback_behavior="Block unless OPENCLAW_PERMISSION_MODE=full_control and record permission.full_control status.",
        requires_confirmation=True,
    ),
    SkillSpec(
        name="xiaoai_utility",
        mode="sandbox",
        description="XiaoAi-compatible daily utilities: time, calculation, unit conversion, jokes, poems, and API-backed Q&A.",
        implemented=True,
        permission_notes="Deterministic utilities run locally; open-ended answers use configured LLM/search APIs.",
        input_contract=("utility text", "optional LLM/search provider configuration"),
        output_contract=("deterministic answer", "needs_llm status", "provider-backed answer when configured"),
        fallback_behavior="Return needs_llm or needs_search instead of inventing unavailable external answers.",
    ),
    SkillSpec(
        name="desktop_safe_actions",
        mode="sandbox",
        description="Open apps, URLs, allowed files, search local files, control media, and adjust volume through deterministic OS commands.",
        implemented=True,
        permission_notes="Read/open actions are constrained to allowed roots. Execution requires OPENCLAW_DESKTOP_BACKEND=local.",
        input_contract=("app alias, URL, allowed file path/query, media command, or volume command",),
        output_contract=("planned action", "opened/launched status", "blocked/unavailable status"),
        fallback_behavior="Default audit_only backend records a plan without changing the desktop.",
    ),
    SkillSpec(
        name="smart_home_bridge",
        mode="sandbox",
        description="Control smart-home devices through Home Assistant REST or a user-provided webhook bridge.",
        implemented=True,
        permission_notes="Requires explicit smart-home provider configuration and mapped device entities.",
        input_contract=("natural-language device command", "configured entity map"),
        output_contract=("parsed command", "bridge call status", "needs_config status"),
        fallback_behavior="Return needs_config unless a Home Assistant or webhook bridge is explicitly configured.",
    ),
    SkillSpec(
        name="mobile_bridge",
        mode="full_control",
        description="Phone calls, SMS, and find-phone workflows through a configured phone companion webhook.",
        implemented=True,
        permission_notes="Requires phone-side OS authorization; calls and SMS require explicit user authorization.",
        input_contract=("phone-side authorized action request", "OPENCLAW_MOBILE_BRIDGE_WEBHOOK_URL"),
        output_contract=("parsed mobile action", "needs_config/needs_confirmation/sent status", "audit event"),
        fallback_behavior="Return needs_config unless a phone companion webhook is explicitly configured.",
        requires_confirmation=True,
        status="adapter_ready",
    ),
    SkillSpec(
        name="p0_office",
        mode="sandbox",
        description="Core office assistant workflows: meeting follow-up package, agenda/reminders, local content search, screen OCR summary, safe desktop actions, and audit status.",
        implemented=True,
        permission_notes="Uses local workspace and allowed roots. External sending or full desktop control still requires confirmation.",
        input_contract=("active meeting session", "workspace files", "allowed-root query", "projection flag"),
        output_contract=("minutes", "transcript export", "email draft", "reminders", "projection confirmation"),
        fallback_behavior="Skip optional reminders/projection only when explicitly disabled or when source data is missing.",
    ),
    SkillSpec(
        name="local_file_search",
        mode="sandbox",
        description="Search allowed roots by filename and text snippets, then write an auditable JSON report.",
        implemented=True,
        permission_notes="Only scans workspace and configured OPENCLAW_ALLOWED_ROOTS.",
        input_contract=("query", "limit", "workspace and configured allowed roots"),
        output_contract=("ranked matches", "snippets", "JSON report path"),
        fallback_behavior="Search only existing allowed roots; never fall back to full-disk traversal.",
    ),
    SkillSpec(
        name="screen_context",
        mode="sandbox",
        description="Capture screen, run OCR when backend is installed, and write a screen-context summary.",
        implemented=True,
        permission_notes="Requires explicit user request; needs screenshot and OCR binaries installed for full output.",
        input_contract=("explicit capture request", "OCR language"),
        output_contract=("screen snapshot", "OCR text file", "screen-context summary"),
        fallback_behavior="Return unavailable or needs_backend when screenshot/OCR binaries are absent.",
        status="adapter_ready",
    ),
    SkillSpec(
        name="lelamp_affordance",
        mode="sandbox",
        description="LeLamp-specific state expression, camera desk observation, projection interaction cards, and environment event inference.",
        implemented=True,
        permission_notes="Hardware and camera access are optional; unavailable backends return auditable degraded results.",
        input_contract=("assistant state", "camera index", "environment sensor reading", "projection card fields"),
        output_contract=("RGB/motion cue", "scene event", "projection card path", "degraded hardware status"),
        fallback_behavior="Return adapter_ready/degraded results when camera, motors, RGB, or projector hardware is absent.",
        status="adapter_ready",
    ),
)


class SkillRegistry:
    def __init__(self, workspace: Workspace, audit: AuditLogger, permission_mode: PermissionMode):
        self.workspace = workspace
        self.audit = audit
        self.permission_mode = permission_mode

    def list_skills(self) -> list[dict[str, object]]:
        self.audit.record("skills.list")
        return [
            {
                "name": skill.name,
                "mode": skill.mode,
                "description": skill.description,
                "implemented": skill.implemented,
                "status": skill.status if skill.implemented else "backend_missing",
                "permission_notes": skill.permission_notes,
                "input_contract": list(skill.input_contract),
                "output_contract": list(skill.output_contract),
                "fallback_behavior": skill.fallback_behavior,
                "requires_confirmation": skill.requires_confirmation,
            }
            for skill in SKILLS
        ]

    def ensure_full_control(self, requested_action: str) -> None:
        if self.permission_mode != PermissionMode.FULL_CONTROL:
            self.audit.record(
                "permission.full_control",
                status="blocked",
                target=requested_action,
                details={"mode": self.permission_mode.value},
            )
            raise PermissionError(
                "Full-control desktop actions are disabled. Set "
                "OPENCLAW_PERMISSION_MODE=full_control after user approval."
            )

        self.audit.record("permission.full_control", target=requested_action)
